#=================================================
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com (chinese)
#=================================================
name: Docker images aria2

on:
  workflow_dispatch:
#  push:
#    branches:
#      - master
#    paths:
#      - 'aria2/*'
  schedule:
    - cron: '30 2 * * 2,5'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: update 
      run: |
        cd aria2
        git clone --depth 1 -b master https://github.com/P3TERX/aria2.conf.git ../aria2conf
        mkdir -p ./conf
        mv ../aria2conf/{aria2.conf,*.sh,*.dat} ./conf/ && rm -rf ../aria2conf
        touch ./conf/aria2.session
        ARIA2_CONF=./conf/aria2.conf
        TRACKER=$(
            curl -fsSL https://trackerslist.com/all_aria2.txt ||
                curl -fsSL https://cdn.jsdelivr.net/gh/XIU2/TrackersListCollection/all_aria2.txt ||
                curl -fsSL https://trackerslist.p3terx.workers.dev/all_aria2.txt ||
                {
                    curl -fsSL https://ngosang.github.io/trackerslist/trackers_all.txt ||
                    curl -fsSL https://cdn.jsdelivr.net/gh/ngosang/trackerslist/trackers_all.txt ||
                        curl -fsSL https://ngosang-trackerslist.p3terx.workers.dev/trackers_all.txt
                } | awk NF | sed ":a;N;s/\n/,/g;ta"
        )
        [ -z $TRACKER ] && echo -e "
        $ERROR Unable to get trackers, network failure or invalid links." && exit 1
        echo -e "
        --------------------[TRACKERS]--------------------
        ${TRACKER}
        --------------------[TRACKERS]--------------------
        "
        [ -z $(grep "bt-tracker=" ${ARIA2_CONF}) ] && echo "bt-tracker=" >>${ARIA2_CONF}
        sed -i "s@^\(bt-tracker=\).*@\1${TRACKER}@" ${ARIA2_CONF} && echo -e "$INFO Trackers added successfully!"
        AriaNg_VER=$(curl -fsSL https://api.github.com/repos/mayswind/AriaNg/releases/latest | grep -o '"tag_name": ".*"' | head -n 1 | sed 's/"//g;s/v//g' | sed 's/tag_name: //g')

    - name: Build and push
      uses: docker/build-push-action@master
      with:
        context: .
        platforms: |
          linux/amd64
        file: aria2/Dockerfile
        build-args: |
          AriaNg_VER=$AriaNg_VER
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/aria2:latest

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.DOCKER_USERNAME }}/aria2
        readme-filepath: aria2/README.md

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 10
        keep_minimum_runs: 10
