on:
  workflow_dispatch:
#  push:
#    branches:
#      - master
#    paths:
#      - 'ubuntu/*'
  schedule:
    - cron: '40 2 * * 5'
name: Docker images openwrt-iwrt

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Login to dokcer Container Registry
        uses: docker/login-action@master
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@master
        with:
          context: .
          platforms: |
            linux/amd64
          file: openwrt/iwrt
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/openwrt:iwrt

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@main
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/openwrt
          readme-filepath: openwrt/README.md
