on:
  workflow_dispatch:
#  push:
#    branches:
#      - master
#    paths:
#      - 'ubuntu/*'
  schedule:
    - cron: '0 3 * * 5'
name: Docker images openwrt

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Login to dokcer Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: update
        run: |
          export Build_Time=$(TZ=UTC-8 date +"%Y%m%d%H%M")
          echo "Build_Time=$Build_Time" >> $GITHUB_ENV
          cd openwrt && ./up.sh

      - name: Build and push
        uses: docker/build-push-action@master
        with:
          context: .
          platforms: |
            linux/amd64
          file: openwrt/Dockerfile
          build-args: |
            Build_Time=${{env.Build_Time}}
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/openwrt:latest
            ${{ secrets.DOCKER_USERNAME }}/openwrt:test
          labels: |
            vsrsion=${{env.Build_Time}}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/openwrt
          readme-filepath: openwrt/README.md

      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 10
          keep_minimum_runs: 10