#=================================================
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com (chinese)
#=================================================
name: Docker images openwrt

on:
  workflow_dispatch:
  push:
#    branches:
#      - master
#    paths:
#      - 'openwrt/*'
  schedule:
    - cron: '20 3 * * 5'
#  watch:
#    types: [started]

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: openwrt-18.06
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: x64.config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: x64.sh
  DIY_P3_SH: x64-2.sh
  TZ: Asia/Shanghai
  GITHUB_REPO: https://github.com/jsda/opbuild

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Install buildx
      run: |
        curl -s https://api.github.com/repos/docker/buildx/releases/latest \
        | grep "browser_download_url.*buildx-*.*linux-amd64" \
        | cut -d : -f 2,3 \
        | tr -d \" \
        | wget -qi -
        mkdir -p ~/.docker/cli-plugins/
        mv buildx* ~/.docker/cli-plugins/docker-buildx
        chmod +x ~/.docker/cli-plugins/docker-buildx
    - name: Set up buildx
      run: |
        docker run --rm --privileged docker/binfmt:66f9012c56a8316f9244ffd7622d7c21c1f6f28d
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker buildx create --use --name multi-arch-builder
    - name: Available platforms
      run: |
        docker buildx inspect --bootstrap | grep Platforms
    - name: Login to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      env:
        PLATFORMS: linux/amd64
        IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/openwrt
        IMAGE_TAG: latest
        DOCKERFILE: Dockerfile
        FILE_PATH: .
      run: |
        cd openwrt
        docker buildx build --push \
          --platform ${PLATFORMS} \
          -t ${IMAGE_NAME}:${IMAGE_TAG} \
          -f ${DOCKERFILE} \
          --build-arg REPO_URL=$REPO_URL \
          --build-arg REPO_BRANCH=$REPO_BRANCH \
          --build-arg FEEDS_CONF=$FEEDS_CONF \
          --build-arg CONFIG_FILE=$CONFIG_FILE \
          --build-arg DIY_P1_SH=$DIY_P1_SH \
          --build-arg DIY_P2_SH=$DIY_P2_SH \
          --build-arg DIY_P3_SH=$DIY_P3_SH \
          --build-arg GITHUB_REPO=$GITHUB_REPO \
          ${FILE_PATH}

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1
